### ISSUE TITLE
Life Version: Error message when attempting to open Agriculture Module

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#46] opened 2021-10-18 12:18 UTC
<img width="1440" alt="211018_agriculture-liver-version" src="https://user-images.githubusercontent.com/90847414/137728653-2d219f2e-9564-4f88-a7b6-6d6b631fea05.png">

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1049, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 424

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1065, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1051, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.actions.act_window(424,).search_view', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1269, in load
    action = request.env[action_type].browse([action_id]).read()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 202, in read
    result = super(IrActionsActWindow, self).read(fields, load=load)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2835, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 5167, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1069, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1182, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1136, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1127, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions.py", line 162, in _compute_search_view
    fvg = self.env[act.res_model].fields_view_get(act.search_view_id.id, 'search')
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 831, in __getitem__
    return self.registry[model_name]._browse((), self)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
KeyError: 'agri.plantation'

**Comment by treviser** [comment] 2021-10-31 08:53
@candidroot 
Please check at [caboz2.twanda-hosting.ch](url)

Duplicate of [https://github.com/twanda/vertical-agriculture/issues/45](url)

**Closed as completed** 2021-11-01 08:52 UTC
Labels: bug, 1st Priority
